name: CI pipeline

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  run-ci-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - run: make setup
      - run: make run
